### ISSUE TITLE
20M private memory -> 4 M

### ISSUE THREAD

**Issue by vitalfadeev** [cerjones/dg2d#4]
Good day !

I have built and run the demo of dg2d. LDC2.

On my Windows x86_64 it taked 20 M of RAM.

![https://github.com/vitalfadeev/dg2d-improve/raw/master/dg2d-20M.png](https://github.com/vitalfadeev/dg2d-improve/raw/master/dg2d-20M.png)

Is it possible to reduce the size of the allocated memory ? ( expecting ~4 M )

Please locate a way in which I can reduce memory usage.

**Comment by p0nce** [comment]
If you build with DMD and -profile=gc it should output a list of GC allocation locations.

**Comment by cerjones** [comment]
Its probably the Canvas.resize and the Window.wm_Paint functions. They are both leaky, ive fixed it on my local branch but I need to do a few more things before I upload it. Tbh there were a  bunch of things I just threw together at the start and then forgot about.

**Comment by cerjones** [comment]
Can you see if the new version is any better? One thing to note is that the demo has two canvas instances, one for the Window class, and there's another one used by the profiling code, so that's 5MB just for those.

**Comment by vitalfadeev** [comment]
Yes. Thanks. Result: https://github.com/vitalfadeev/dg2d-improve/blob/master/2/README.md
Two instance - I got it.

**Comment by vitalfadeev** [comment]
i looked at simple GDI app: https://github.com/vitalfadeev/dg2d-improve/blob/master/2/GDI.md
...and expected a similar size.

**Comment by cerjones** [comment]
Still looks like it's using 20MB? On my machine (windows 7) it uses 10MB, so i dont know why it's using more on yours. I think a GDI app would use less memory anyway since theres no need for an intermediate buffer to draw too. Anyway I could add some logging quite easily since i wrapped malloc/realloc/free, so I just have one place to look at. And then also profile GC allocations as ponce suggested. I'll have a look at it tonight or tomorrow.

**Comment by p0nce** [comment]
Could it can be 32-bit vs 64-bit? Depending on the OS and bitness, the GC can incur larger memory usage because of "false pointers". At least that was the case a while ago.

**Comment by cerjones** [comment]
I just tried 32 vs 64 bit, 32 does use a bit less memory but not much. 

I added some logging to the malloc/free/realloc wrappers in misc.d, and theres 6MB of memory allocated on the c heap at startup. And total memory use reported in task Manager for me is just over 8MB. Doesnt seem to bad since there's 5MB of pixel buffers.

There shouldn't be much GC usage, just a few objects, nothing massive.

So Im a bit stumped, best guess is something to do with widows 10 maybe?

**Comment by vitalfadeev** [comment]
Nice! ...
Calculations show me also 7-11 M
```
1. .exe: code + data    ~ 1 MB
2. .so | .dll libraries ~ ...
3. heap                 ~ 6 M
4. buffer 800 x 800 x 4 = 2.560 MB ( from heap? )
5. double buffer        = 2.560 MB ( from heap? )
                          --------
                        ~ 7-11 MB
```

**Comment by vitalfadeev** [comment]
)
I run 3 tools...
1 showed 10,
2 showed 10,
3 showed 20
))

![](https://github.com/vitalfadeev/dg2d-improve/raw/master/3-mem-tools.png)
.
... 2 threads summed...

**Comment by cerjones** [comment]
That seems about right, 7 .. 11MB, not sure why Process Explorer shows 20MB.

**Comment by p0nce** [comment]
It's a problem for who? AFAIK dg2d allocates only minimal memory, and take an external buffer. Memory of the example is not really relevant right?

**Comment by cerjones** [comment]
Yeah should be very little in normal usage. I think he was getting double what the demo should be but looks like process explorer is reporting it wrong. Dont know tbh. But i think this can be closed.
